### ISSUE TITLE
Network maintenance impacting several sites

### ISSUE THREAD

**Issue by paul999** [phpbb/status-site#52]
Our hosting provider will be performing network maintenance which will impact several of our sites. This might cause a downtime for around 10 minutes.
This maintenance might cause your version check to show a temporary error, however non phpBB.com sites should keep working.

**Comment by marc1706** [comment]
Our hosting provider will be performing network maintenance which will impact several of our sites. This might cause a downtime for around 10 minutes.
This maintenance might cause your version check to show a temporary error, however non phpBB.com sites should keep working.
